### ISSUE TITLE
Record subscribe "triggerNow" issue

### ISSUE THREAD

**Issue by lmacsen** [hoxton-one/deepstream.io-client-js#19]
Hi,

I have a problem with Record's subscribe function. If it has a value in cache connector, it executes the callback function immediately and not only on the record's value changes.

My case scenario is an isomorphic application that will render on server at first request and then will listen for changes in the client side.

```javascript
var ds = deepstream('localhost:6020').login();
var user = ds.record.getRecord('user/14');

user.subscribe('age', function(age) {
  // This will be called if has a value in cache connector
  console.log('Happy Birthday !!!');
}, false);

```

Thank you for your greak work at this library.

**Comment by WolframHempel** [comment]
Hi @lmacsen ,

thanks for raising this. When a record hasn't been loaded yet (e.g. when the application calls `ds.record.getRecord('user/14')` for the first time) it's value is `null` - so data coming in for the first time triggers all subscribe functions. This is usually the desired behavior for applications that are designed around data-pipelines.

If you'd like to only process explicit changes, just bind the callback once the record is ready. For your example above that would look as follows:

```javascript
var ds = deepstream('localhost:6020').login();
var user = ds.record.getRecord('user/14');

user.whenReady(function(){
    user.subscribe('age', function(age) {
     // This will be called if has a value in cache connector
     console.log('Happy Birthday !!!');
   });
});
```

please let me know if that solves your issue,

best,
Wolfram

**Comment by lmacsen** [comment]
Oh, that's it. Thank you so much Wolfram.

**Comment by lmacsen** [comment]
Hi again,

Acording to documentation List should have the same behaviour. I'm doing something wrong?

```javascript
var list = ds.record.getList('users');
list.whenReady(function () {
  list.subscribe(function (entries) {
    // This will be called immediately with the current value
    console.log(entries);
  }, false);
});
```

Thanks.

**Comment by yasserf** [comment]
hey,

What you were doing is correct, and turned out to be a bug which we now have a PR for. Lists are currently purely an extension of records with extra API functionality for entry management. It turns out the subscribe( callback ) would trigger within whenReady regardless of the triggerNow flag for both lists and records when not providing a path.

Many thanks for raising this issue! And very sorry for the long delay in replying. We are now focusing our attention much more on deepstream development as part of [deepstreamhub](http://deepstreamhub.com/) so this should not be recurring theme!
